title: samuelsmal
email: savoba@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Another blog! Woobwoob!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samuelsmal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: samuelsmal


lsi: false
safe: true
incremental: false

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections_dir: collections
collections:
  collections:
    output: true
    permalink: /:collection/:name
  drafts:
    output: false
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:name



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - Makefile
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
